# main/resources/application-local.yml

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/booking_db
    username: book_user
    password: book_1234
  # ğŸ‘‡ ì´ë©”ì¼ ì„¤ì •ì„ local í”„ë¡œí•„ì— ì¶”ê°€í•©ë‹ˆë‹¤.
  mail:
    username: "${SPRING_MAIL_USERNAME}"
    password: "${SPRING_MAIL_PASSWORD}"

# ğŸ‘‡ JWT ì„¤ì •ì„ local í”„ë¡œí•„ì— ì¶”ê°€í•©ë‹ˆë‹¤.
jwt:
  secret:
    key: a2Fì¹´ì˜¤ë””ì˜¤a2FkaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaQ==

#JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE