# main/resources/application-local.yml

spring:
  config:
    activate:
      on-profile: local

  # --- ë¡œì»¬ DB ì„¤ì • ---
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/booking_db
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
  mail:
    username: "${SPRING_MAIL_USERNAME}"
    password: "${SPRING_MAIL_PASSWORD}"
# ğŸ‘‡ JWT ì„¤ì •ì„ local í”„ë¡œí•„ì— ì¶”ê°€í•©ë‹ˆë‹¤.
jwt:
  secret:
    key: a2Fì¹´ì˜¤ë””ì˜¤a2FkaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaW9kaQ==

# --- OAuth2 ë¡œì»¬ ë¦¬ë‹¤ì´ë ‰íŠ¸ URI ---
app:
  oauth2:
    authorized-redirect-uri: http://localhost:80/homepage

# --- ë¡œì»¬ ê°œë°œìš© ìƒì„¸ ë¡œê·¸ ---
logging:
  level:
    root: INFO
    com.example.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG

toss:
  payments:
    #  ë°±ì—”ë“œ ì „ìš©: ê²°ì œ ìŠ¹ì¸/ì·¨ì†Œ ì‹œ ì„œë²„ì—ì„œë§Œ ì‚¬ìš©í•˜ëŠ” ë¹„ë°€ í‚¤
    secret-key: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6 "
